//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORSE
    {
        public int HORSE_ID { get; set; }
        public string HORSE_name { get; set; }
        public int HORSE_age { get; set; }
        public Nullable<int> FK_HORSE_breedID { get; set; }
        public bool HORSE_sex { get; set; }
        public int FK_USER_ID_HORSE { get; set; }
    
        public virtual BREED BREED { get; set; }
        public virtual USER USER { get; set; }
    }
}
