//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.HORSEs = new HashSet<HORSE>();
            this.LISTs = new HashSet<LIST>();
        }
    
        public int USER_ID { get; set; }
        public string USER_name { get; set; }
        public string USER_surname { get; set; }
        public string USER_email { get; set; }
        public string USER_phone { get; set; }
        public int USER_age { get; set; }
        public string USER_login { get; set; }
        public string USER_password { get; set; }
        public bool USER_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORSE> HORSEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIST> LISTs { get; set; }
    }
}
