//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorseClubDBEntities : DbContext
    {
        public HorseClubDBEntities()
            : base("name=HorseClubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BREED> BREEDs { get; set; }
        public virtual DbSet<event_type> event_type { get; set; }
        public virtual DbSet<EVENT> EVENTS { get; set; }
        public virtual DbSet<HORSE> HORSEs { get; set; }
        public virtual DbSet<LIST> LISTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
