//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMISIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMISIN()
        {
            this.EMP_COM = new HashSet<EMP_COM>();
        }
    
        public int commission_id { get; set; }
        public string client_name { get; set; }
        public string client_surname { get; set; }
        public string client_last_name { get; set; }
        public string com_city { get; set; }
        public string com_place { get; set; }
        public string com_tel_number { get; set; }
        public Nullable<int> ID_CONTENT_TYPE { get; set; }
        public Nullable<int> ID_TECH { get; set; }
        public Nullable<System.DateTime> com_date { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Tech Tech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_COM> EMP_COM { get; set; }
    }
}
