//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp()
        {
            this.EMP_COM = new HashSet<EMP_COM>();
        }
    
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_surname { get; set; }
        public string emp_last_name { get; set; }
        public string emp_phone_number { get; set; }
        public string emp_email { get; set; }
        public Nullable<System.DateTime> emp_date_of_birth { get; set; }
        public Nullable<int> emp_status { get; set; }
        public Nullable<int> ID_DOCKPACK { get; set; }
    
        public virtual Doc Doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_COM> EMP_COM { get; set; }
    }
}
