//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_COM
    {
        public int empcom_id { get; set; }
        public Nullable<int> ID_EMP { get; set; }
        public Nullable<int> ID_COM { get; set; }
    
        public virtual COMMISIN COMMISIN { get; set; }
        public virtual Emp Emp { get; set; }
    }
}
