//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tech()
        {
            this.COMMISINs = new HashSet<COMMISIN>();
        }
    
        public int tech_id { get; set; }
        public string tech_model { get; set; }
        public string tech_label { get; set; }
        public string tech_series_number { get; set; }
        public Nullable<int> tech_year_of_prod { get; set; }
        public Nullable<int> tech_status { get; set; }
        public string tech_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMISIN> COMMISINs { get; set; }
    }
}
